/**
 * https://github.com/stormwarning/stylelint-config-recess-order/blob/main/index.js
 * https://github.com/stormwarning/stylelint-config-recess-order/blob/main/groups.js
 * commit: 33f7e8d7460ca99b5dcf82f6e4aba4806b79c8cf
 */

import { generator } from "./generator.js"
import baseConfig from "./stylelint-base.config.js"
import type { OrderData } from "./generator.js"
import type { Config } from "stylelint"

const order: Record<string, string[]> = {
	"composes": [],
	"all": [],
	"position": [],
	"inset": [],
	"inset-block": [],
	"inset-block-start": [],
	"inset-block-end": [],
	"inset-inline": [],
	"inset-inline-start": [],
	"inset-inline-end": [],
	"top": [],
	"right": [],
	"bottom": [],
	"left": [],
	"z-index": [],
	"float": [],
	"clear": [],
	"box-sizing": [],
	"display": [],
	"visibility": [],
	"flex": [],
	"flex-grow": [],
	"flex-shrink": [],
	"flex-basis": [],
	"flex-flow": [],
	"flex-direction": [],
	"flex-wrap": [],
	// "-webkit-box-orient": [], // Vendor prefix
	"grid": [],
	"grid-area": [],
	"grid-template": [],
	"grid-template-areas": [],
	"grid-template-rows": [],
	"grid-template-columns": [],
	"grid-row": [],
	"grid-row-start": [],
	"grid-row-end": [],
	"grid-column": [],
	"grid-column-start": [],
	"grid-column-end": [],
	"grid-auto-rows": [],
	"grid-auto-columns": [],
	"grid-auto-flow": [],
	"grid-gap": [],
	"grid-row-gap": [],
	"grid-column-gap": [],
	"gap": [],
	"row-gap": [],
	"column-gap": [],
	"place-content": [],
	"place-items": [],
	"place-self": [],
	"align-content": [],
	"align-items": [],
	"align-self": [],
	"justify-content": [],
	"justify-items": [],
	"justify-self": [],
	"order": [],
	"block-size": [], // Shifted (new position)
	"min-block-size": [], // Shifted (new position)
	"max-block-size": [], // Shifted (new position)
	"inline-size": [],
	"min-inline-size": [],
	"max-inline-size": [],
	"width": [],
	"min-width": [],
	"max-width": [],
	// "block-size": [], // Shifted (previous position)
	// "min-block-size": [], // Shifted (previous position)
	// "max-block-size": [], // Shifted (previous position)
	"height": [],
	"min-height": [],
	"max-height": [],
	"aspect-ratio": [],
	"padding": [],
	"padding-block": [],
	"padding-block-start": [],
	"padding-block-end": [],
	"padding-inline": [],
	"padding-inline-start": [],
	"padding-inline-end": [],
	"padding-top": [],
	"padding-right": [],
	"padding-bottom": [],
	"padding-left": [],
	"margin": [],
	"margin-block": [],
	"margin-block-start": [],
	"margin-block-end": [],
	"margin-inline": [],
	"margin-inline-start": [],
	"margin-inline-end": [],
	"margin-top": [],
	"margin-right": [],
	"margin-bottom": [],
	"margin-left": [],
	"overflow": [],
	"overflow-block": [], // Shifted up one
	"overflow-inline": [], // Shifted down one
	"overflow-x": [],
	"overflow-y": [],
	"scrollbar-gutter": [],
	// "-webkit-overflow-scrolling": [], // Vendor prefix
	// "-ms-overflow-x": [], // Vendor prefix
	// "-ms-overflow-y": [], // Vendor prefix
	// "-ms-overflow-style": [], // Vendor prefix
	"text-overflow": [],
	// "-webkit-line-clamp": [], // Vendor prefix
	"line-clamp": [],
	"scroll-behaviour": [],
	"overscroll-behavior": [],
	"overscroll-behavior-block": [], // Shifted up one
	"overscroll-behavior-inline": [], // Shifted down one
	"overscroll-behavior-x": [],
	"overscroll-behavior-y": [],
	"font": [],
	"font-family": [],
	"font-size": [],
	"font-size-adjust": [],
	"font-variation-settings": [],
	"font-style": [],
	"font-weight": [],
	"font-optical-sizing": [],
	"font-stretch": [],
	"font-feature-settings": [],
	"font-kerning": [],
	"font-variant": [],
	"font-variant-ligatures": [],
	"font-variant-caps": [],
	"font-variant-alternates": [],
	"font-variant-numeric": [],
	"font-variant-east-asian": [],
	"font-variant-position": [],
	// "-webkit-font-smoothing": [], // Vendor prefix
	// "-moz-osx-font-smoothing": [], // Vendor prefix
	"font-smooth": [],
	"line-height": [],
	"vertical-align": [],
	"alignment-baseline": [],
	"baseline-shift": [],
	"dominant-baseline": [],
	"color": [],
	// "-webkit-text-fill-color": [], // Vendor prefix
	// "-webkit-text-stroke": [], // Vendor prefix
	// "-webkit-text-stroke-width": [], // Vendor prefix
	// "-webkit-text-stroke-color": [], // Vendor prefix
	"text-align": [],
	"text-align-last": [],
	"text-justify": [],
	"text-indent": [],
	"text-transform": [],
	"word-spacing": [],
	"letter-spacing": [],
	"hyphens": [],
	"word-break": [],
	"text-wrap": [],
	"word-wrap": [], // Legacy name for `overflow-wrap`
	"overflow-wrap": [],
	"tab-size": [],
	"white-space": [],
	"text-emphasis": [],
	"text-emphasis-color": [],
	"text-emphasis-style": [],
	"text-emphasis-position": [],
	"text-decoration": [],
	"text-decoration-line": [],
	"text-decoration-thickness": [],
	"text-decoration-style": [],
	"text-decoration-color": [],
	"text-underline-position": [],
	"text-underline-offset": [],
	"text-shadow": [],
	"src": [],
	"font-display": [],
	"unicode-range": [],
	"size-adjust": [],
	"ascent-override": [],
	"descent-override": [],
	"line-gap-override": [],
	"appearance": [],
	"accent-color": [],
	"pointer-events": [],
	// "-ms-touch-action": [], // Vendor prefix
	"touch-action": [],
	"cursor": [],
	"caret-color": [],
	"zoom": [], // ?
	"resize": [],
	"user-select": [],
	// "-webkit-user-select": [], // Vendor prefix
	"nav-index": [],
	"nav-up": [],
	"nav-right": [],
	"nav-down": [],
	"nav-left": [],
	"outline": [],
	"outline-width": [],
	"outline-style": [],
	"outline-color": [],
	"outline-offset": [],
	"color-scheme": [],
	"table-layout": [],
	"empty-cells": [],
	"caption-side": [],
	"border-spacing": [],
	"border-collapse": [],
	"content": [],
	"quotes": [],
	"list-style": [],
	"list-style-position": [],
	"list-style-type": [],
	"list-style-image": [],
	"counter-reset": [],
	"counter-set": [],
	"counter-increment": [],
	"scroll-snap-type": [],
	"scroll-snap-align": [],
	"scroll-snap-stop": [],
	"scroll-padding": [],
	"scroll-padding-block": [],
	"scroll-padding-block-start": [],
	"scroll-padding-block-end": [],
	"scroll-padding-inline": [],
	"scroll-padding-inline-start": [],
	"scroll-padding-inline-end": [],
	"scroll-padding-top": [],
	"scroll-padding-right": [],
	"scroll-padding-bottom": [],
	"scroll-padding-left": [],
	"scroll-margin": [],
	"scroll-margin-block": [],
	"scroll-margin-block-start": [],
	"scroll-margin-block-end": [],
	"scroll-margin-inline": [],
	"scroll-margin-inline-start": [],
	"scroll-margin-inline-end": [],
	"scroll-margin-top": [],
	"scroll-margin-right": [],
	"scroll-margin-bottom": [],
	"scroll-margin-left": [],
	"scrollbar-color": [],
	"scrollbar-width": [],
	"object-fit": [],
	"object-position": [],
	// "-ms-interpolation-mode": [], // Vendor prefix
	"image-orientation": [],
	"image-rendering": [],
	"image-resolution": [],
	"background": [],
	"background-color": [],
	"background-image": [],
	// "-ms-filter:\\'progid:DXImageTransform.Microsoft.gradient": [], // Vendor prefix
	// "filter:progid:DXImageTransform.Microsoft.gradient": [], // Vendor prefix
	// "filter:progid:DXImageTransform.Microsoft.AlphaImageLoader": [], // Vendor prefix
	"background-repeat": [],
	"background-attachment": [],
	"background-position": [],
	"background-position-x": [],
	"background-position-y": [],
	"background-clip": [],
	"background-origin": [],
	"background-size": [],
	"border": [],
	"border-color": [],
	"border-style": [],
	"border-width": [],
	"border-block": [],
	"border-block-start": [],
	"border-block-start-color": [],
	"border-block-start-style": [],
	"border-block-start-width": [],
	"border-block-end": [],
	"border-block-end-color": [],
	"border-block-end-style": [],
	"border-block-end-width": [],
	"border-inline": [],
	"border-inline-start": [],
	"border-inline-start-color": [],
	"border-inline-start-style": [],
	"border-inline-start-width": [],
	"border-inline-end": [],
	"border-inline-end-color": [],
	"border-inline-end-style": [],
	"border-inline-end-width": [],
	"border-top": [],
	"border-top-color": [],
	"border-top-style": [],
	"border-top-width": [],
	"border-right": [],
	"border-right-color": [],
	"border-right-style": [],
	"border-right-width": [],
	"border-bottom": [],
	"border-bottom-color": [],
	"border-bottom-style": [],
	"border-bottom-width": [],
	"border-left": [],
	"border-left-color": [],
	"border-left-style": [],
	"border-left-width": [],
	"border-radius": [],
	"border-start-start-radius": [],
	"border-start-end-radius": [],
	"border-end-start-radius": [],
	"border-end-end-radius": [],
	"border-top-left-radius": [],
	"border-top-right-radius": [],
	"border-bottom-right-radius": [],
	"border-bottom-left-radius": [],
	"border-image": [],
	"border-image-source": [],
	"border-image-slice": [],
	"border-image-width": [],
	"border-image-outset": [],
	"border-image-repeat": [],
	"box-shadow": [],
	"background-blend-mode": [],
	"isolation": [],
	"mix-blend-mode": [],
	// "filter:progid:DXImageTransform.Microsoft.Alpha(Opacity": [], // Vendor prefix
	// "-ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha": [], // Vendor prefix
	"opacity": [],
	"filter": [],
	"backdrop-filter": [],
	"clip": [],
	"clip-path": [],
	"mask-border": [],
	"mask-border-source": [],
	"mask-border-slice": [],
	"mask-border-width": [],
	"mask-border-outset": [],
	"mask-border-repeat": [],
	"mask-border-mode": [],
	"mask": [],
	"mask-image": [],
	"mask-mode": [],
	"mask-repeat": [],
	"mask-position": [],
	"mask-clip": [],
	"mask-origin": [],
	"mask-size": [],
	"mask-composite": [],
	"writing-mode": [],
	"text-anchor": [],
	"fill": [],
	"fill-rule": [],
	"fill-opacity": [],
	"stroke": [],
	"stroke-opacity": [],
	"stroke-width": [],
	"stroke-linecap": [],
	"stroke-linejoin": [],
	"stroke-miterlimit": [],
	"stroke-dasharray": [],
	"stroke-dashoffset": [],
	"color-interpolation": [],
	"color-interpolation-filters": [],
	"flood-color": [],
	"flood-opacity": [],
	"lighting-color": [],
	"marker-start": [],
	"marker-mid": [],
	"marker-end": [],
	"stop-color": [],
	"stop-opacity": [],
	"shape-rendering": [],
	"transform": [],
	"transform-origin": [],
	"rotate": [],
	"scale": [],
	"translate": [],
	"perspective": [],
	"perspective-origin": [],
	"transition": [],
	"transition-delay": [],
	"transition-timing-function": [],
	"transition-duration": [],
	"transition-property": [],
	"animation": [],
	"animation-name": [],
	"animation-duration": [],
	"animation-timing-function": [],
	"animation-delay": [],
	"animation-iteration-count": [],
	"animation-direction": [],
	"animation-play-state": [],
	"will-change": [],
	"break-before": [],
	"break-after": [],
	"break-inside": [],
	"widows": [],
	"orphans": [],
}

export async function generateRecess (source: string, stylelintrcPath: string): Promise<Record<"order", OrderData[]>> {
	const config: Config = {
		...baseConfig,
		"extends": ["stylelint-config-recess-order"],
	}

	return await generator({ config, order, source, stylelintrcPath })
}
