import baseConfig from "./stylelint-base.config.js"
import type { Config } from "stylelint"

export interface StylelintConfigOrder {
	config: Config & { "extends": string[] },
	order: Record<string, string[]>,
}

// https://github.com/stormwarning/stylelint-config-recess-order/blob/main/index.js
// https://github.com/stormwarning/stylelint-config-recess-order/blob/main/groups.js
// commit: 33f7e8d7460ca99b5dcf82f6e4aba4806b79c8cf
export const recessConfigOrder: StylelintConfigOrder = {
	config: {
		...baseConfig,
		"extends": ["stylelint-config-recess-order"],
	},
	order: {
		"composes": [],
		"all": [],
		"position": [],
		"inset": [],
		"inset-block": [],
		"inset-block-start": [],
		"inset-block-end": [],
		"inset-inline": [],
		"inset-inline-start": [],
		"inset-inline-end": [],
		"top": [],
		"right": [],
		"bottom": [],
		"left": [],
		"z-index": [],
		"float": [],
		"clear": [],
		"box-sizing": [],
		"display": [],
		"visibility": [],
		"flex": [],
		"flex-grow": [],
		"flex-shrink": [],
		"flex-basis": [],
		"flex-flow": [],
		"flex-direction": [],
		"flex-wrap": [],
		"-webkit-box-orient": [], // Vendor prefix
		"grid": [],
		"grid-area": [],
		"grid-template": [],
		"grid-template-areas": [],
		"grid-template-rows": [],
		"grid-template-columns": [],
		"grid-row": [],
		"grid-row-start": [],
		"grid-row-end": [],
		"grid-column": [],
		"grid-column-start": [],
		"grid-column-end": [],
		"grid-auto-rows": [],
		"grid-auto-columns": [],
		"grid-auto-flow": [],
		"grid-gap": [],
		"grid-row-gap": [],
		"grid-column-gap": [],
		"gap": [],
		"row-gap": [],
		"column-gap": [],
		"place-content": [],
		"place-items": [],
		"place-self": [],
		"align-content": [],
		"align-items": [],
		"align-self": [],
		"justify-content": [],
		"justify-items": [],
		"justify-self": [],
		"order": [],
		"block-size": [], // Shifted (new position)
		"min-block-size": [], // Shifted (new position)
		"max-block-size": [], // Shifted (new position)
		"inline-size": [],
		"min-inline-size": [],
		"max-inline-size": [],
		"width": [],
		"min-width": [],
		"max-width": [],
		// "block-size": [], // Shifted (previous position)
		// "min-block-size": [], // Shifted (previous position)
		// "max-block-size": [], // Shifted (previous position)
		"height": [],
		"min-height": [],
		"max-height": [],
		"aspect-ratio": [],
		"padding": [],
		"padding-block": [],
		"padding-block-start": [],
		"padding-block-end": [],
		"padding-inline": [],
		"padding-inline-start": [],
		"padding-inline-end": [],
		"padding-top": [],
		"padding-right": [],
		"padding-bottom": [],
		"padding-left": [],
		"margin": [],
		"margin-block": [],
		"margin-block-start": [],
		"margin-block-end": [],
		"margin-inline": [],
		"margin-inline-start": [],
		"margin-inline-end": [],
		"margin-top": [],
		"margin-right": [],
		"margin-bottom": [],
		"margin-left": [],
		"overflow": [],
		"overflow-block": [], // Shifted up one
		"overflow-inline": [], // Shifted down one
		"overflow-x": [],
		"overflow-y": [],
		"scrollbar-gutter": [],
		"-webkit-overflow-scrolling": [], // Vendor prefix
		"-ms-overflow-x": [], // Vendor prefix
		"-ms-overflow-y": [], // Vendor prefix
		"-ms-overflow-style": [], // Vendor prefix
		"text-overflow": [],
		"-webkit-line-clamp": [], // Vendor prefix
		"line-clamp": [],
		"scroll-behavior": [], // scroll-behaviour -> scroll-behavior
		"overscroll-behavior": [],
		"overscroll-behavior-block": [], // Shifted up one
		"overscroll-behavior-inline": [], // Shifted down one
		"overscroll-behavior-x": [],
		"overscroll-behavior-y": [],
		"font": [],
		"font-family": [],
		"font-size": [],
		"font-size-adjust": [],
		"font-variation-settings": [],
		"font-style": [],
		"font-weight": [],
		"font-optical-sizing": [],
		"font-stretch": [],
		"font-feature-settings": [],
		"font-kerning": [],
		"font-variant": [],
		"font-variant-ligatures": [],
		"font-variant-caps": [],
		"font-variant-alternates": [],
		"font-variant-numeric": [],
		"font-variant-east-asian": [],
		"font-variant-position": [],
		"-webkit-font-smoothing": [], // Vendor prefix
		"-moz-osx-font-smoothing": [], // Vendor prefix
		"font-smooth": [],
		"line-height": [],
		"vertical-align": [],
		"alignment-baseline": [],
		"baseline-shift": [],
		"dominant-baseline": [],
		"color": [],
		"-webkit-text-fill-color": [], // Vendor prefix
		"-webkit-text-stroke": [], // Vendor prefix
		"-webkit-text-stroke-width": [], // Vendor prefix
		"-webkit-text-stroke-color": [], // Vendor prefix
		"text-align": [],
		"text-align-last": [],
		"text-justify": [],
		"text-indent": [],
		"text-transform": [],
		"word-spacing": [],
		"letter-spacing": [],
		"hyphens": [],
		"word-break": [],
		"text-wrap": [],
		"word-wrap": [], // Legacy name for `overflow-wrap`
		"overflow-wrap": [],
		"tab-size": [],
		"white-space": [],
		"text-emphasis": [],
		"text-emphasis-color": [],
		"text-emphasis-style": [],
		"text-emphasis-position": [],
		"text-decoration": [],
		"text-decoration-line": [],
		"text-decoration-thickness": [],
		"text-decoration-style": [],
		"text-decoration-color": [],
		"text-underline-position": [],
		"text-underline-offset": [],
		"text-shadow": [],
		"src": [],
		"font-display": [],
		"unicode-range": [],
		"size-adjust": [],
		"ascent-override": [],
		"descent-override": [],
		"line-gap-override": [],
		"appearance": [],
		"accent-color": [],
		"pointer-events": [],
		"-ms-touch-action": [], // Vendor prefix
		"touch-action": [],
		"cursor": [],
		"caret-color": [],
		"zoom": [], // ?
		"resize": [],
		"user-select": [],
		"-webkit-user-select": [], // Vendor prefix
		"nav-index": [],
		"nav-up": [],
		"nav-right": [],
		"nav-down": [],
		"nav-left": [],
		"outline": [],
		"outline-width": [],
		"outline-style": [],
		"outline-color": [],
		"outline-offset": [],
		"color-scheme": [],
		"table-layout": [],
		"empty-cells": [],
		"caption-side": [],
		"border-spacing": [],
		"border-collapse": [],
		"content": [],
		"quotes": [],
		"list-style": [],
		"list-style-position": [],
		"list-style-type": [],
		"list-style-image": [],
		"counter-reset": [],
		"counter-set": [],
		"counter-increment": [],
		"scroll-snap-type": [],
		"scroll-snap-align": [],
		"scroll-snap-stop": [],
		"scroll-padding": [],
		"scroll-padding-block": [],
		"scroll-padding-block-start": [],
		"scroll-padding-block-end": [],
		"scroll-padding-inline": [],
		"scroll-padding-inline-start": [],
		"scroll-padding-inline-end": [],
		"scroll-padding-top": [],
		"scroll-padding-right": [],
		"scroll-padding-bottom": [],
		"scroll-padding-left": [],
		"scroll-margin": [],
		"scroll-margin-block": [],
		"scroll-margin-block-start": [],
		"scroll-margin-block-end": [],
		"scroll-margin-inline": [],
		"scroll-margin-inline-start": [],
		"scroll-margin-inline-end": [],
		"scroll-margin-top": [],
		"scroll-margin-right": [],
		"scroll-margin-bottom": [],
		"scroll-margin-left": [],
		"scrollbar-color": [],
		"scrollbar-width": [],
		"object-fit": [],
		"object-position": [],
		"-ms-interpolation-mode": [], // Vendor prefix
		"image-orientation": [],
		"image-rendering": [],
		"image-resolution": [],
		"background": [],
		"background-color": [],
		"background-image": [],
		// "-ms-filter:\\'progid:DXImageTransform.Microsoft.gradient": [], // Vendor prefix
		// "filter:progid:DXImageTransform.Microsoft.gradient": [], // Vendor prefix
		// "filter:progid:DXImageTransform.Microsoft.AlphaImageLoader": [], // Vendor prefix
		"background-repeat": [],
		"background-attachment": [],
		"background-position": [],
		"background-position-x": [],
		"background-position-y": [],
		"background-clip": [],
		"background-origin": [],
		"background-size": [],
		"border": [],
		"border-color": [],
		"border-style": [],
		"border-width": [],
		"border-block": [],
		"border-block-start": [],
		"border-block-start-color": [],
		"border-block-start-style": [],
		"border-block-start-width": [],
		"border-block-end": [],
		"border-block-end-color": [],
		"border-block-end-style": [],
		"border-block-end-width": [],
		"border-inline": [],
		"border-inline-start": [],
		"border-inline-start-color": [],
		"border-inline-start-style": [],
		"border-inline-start-width": [],
		"border-inline-end": [],
		"border-inline-end-color": [],
		"border-inline-end-style": [],
		"border-inline-end-width": [],
		"border-top": [],
		"border-top-color": [],
		"border-top-style": [],
		"border-top-width": [],
		"border-right": [],
		"border-right-color": [],
		"border-right-style": [],
		"border-right-width": [],
		"border-bottom": [],
		"border-bottom-color": [],
		"border-bottom-style": [],
		"border-bottom-width": [],
		"border-left": [],
		"border-left-color": [],
		"border-left-style": [],
		"border-left-width": [],
		"border-radius": [],
		"border-start-start-radius": [],
		"border-start-end-radius": [],
		"border-end-start-radius": [],
		"border-end-end-radius": [],
		"border-top-left-radius": [],
		"border-top-right-radius": [],
		"border-bottom-right-radius": [],
		"border-bottom-left-radius": [],
		"border-image": [],
		"border-image-source": [],
		"border-image-slice": [],
		"border-image-width": [],
		"border-image-outset": [],
		"border-image-repeat": [],
		"box-shadow": [],
		"background-blend-mode": [],
		"isolation": [],
		"mix-blend-mode": [],
		// "filter:progid:DXImageTransform.Microsoft.Alpha(Opacity": [], // Vendor prefix
		// "-ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha": [], // Vendor prefix
		"opacity": [],
		"filter": [],
		"backdrop-filter": [],
		"clip": [],
		"clip-path": [],
		"mask-border": [],
		"mask-border-source": [],
		"mask-border-slice": [],
		"mask-border-width": [],
		"mask-border-outset": [],
		"mask-border-repeat": [],
		"mask-border-mode": [],
		"mask": [],
		"mask-image": [],
		"mask-mode": [],
		"mask-repeat": [],
		"mask-position": [],
		"mask-clip": [],
		"mask-origin": [],
		"mask-size": [],
		"mask-composite": [],
		"writing-mode": [],
		"text-anchor": [],
		"fill": [],
		"fill-rule": [],
		"fill-opacity": [],
		"stroke": [],
		"stroke-opacity": [],
		"stroke-width": [],
		"stroke-linecap": [],
		"stroke-linejoin": [],
		"stroke-miterlimit": [],
		"stroke-dasharray": [],
		"stroke-dashoffset": [],
		"color-interpolation": [],
		"color-interpolation-filters": [],
		"flood-color": [],
		"flood-opacity": [],
		"lighting-color": [],
		"marker-start": [],
		"marker-mid": [],
		"marker-end": [],
		"stop-color": [],
		"stop-opacity": [],
		"shape-rendering": [],
		"transform": [],
		"transform-origin": [],
		"rotate": [],
		"scale": [],
		"translate": [],
		"perspective": [],
		"perspective-origin": [],
		"transition": [],
		"transition-delay": [],
		"transition-timing-function": [],
		"transition-duration": [],
		"transition-property": [],
		"animation": [],
		"animation-name": [],
		"animation-duration": [],
		"animation-timing-function": [],
		"animation-delay": [],
		"animation-iteration-count": [],
		"animation-direction": [],
		"animation-play-state": [],
		"will-change": [],
		"break-before": [],
		"break-after": [],
		"break-inside": [],
		"widows": [],
		"orphans": [],
	},
}

// https://github.com/chaucerbao/stylelint-config-concentric-order/blob/master/src/index.js
// commit: 8a7ee43e5986dbbf699df1c73fb0eeb345ff6e99
export const concentricConfigOrder: StylelintConfigOrder = {
	config: {
		...baseConfig,
		"extends": ["stylelint-config-concentric-order"],
	},
	order: {
		"all": [],
		"appearance": [],
		"box-sizing": [],
		"display": [],
		"position": [],
		"inset": [],
		"inset-block": [],
		"inset-block-start": [],
		"inset-block-end": [],
		"inset-inline": [],
		"inset-inline-start": [],
		"inset-inline-end": [],
		"top": [],
		"right": [],
		"bottom": [],
		"left": [],
		"float": [],
		"clear": [],
		"flex": [],
		"flex-basis": [],
		"flex-direction": [],
		"flex-flow": [],
		"flex-grow": [],
		"flex-shrink": [],
		"flex-wrap": [],
		"grid": [],
		"grid-area": [],
		"grid-template": [],
		"grid-template-areas": [],
		"grid-template-rows": [],
		"grid-template-columns": [],
		"grid-row": [],
		"grid-row-start": [],
		"grid-row-end": [],
		"grid-column": [],
		"grid-column-start": [],
		"grid-column-end": [],
		"grid-auto-rows": [],
		"grid-auto-columns": [],
		"grid-auto-flow": [],
		"gap": [],
		"grid-gap": [],
		"row-gap": [],
		"grid-row-gap": [],
		"column-gap": [],
		"grid-column-gap": [],
		"place-content": [],
		"place-items": [],
		"place-self": [],
		"align-content": [],
		"align-items": [],
		"align-self": [],
		"justify-content": [],
		"justify-items": [],
		"justify-self": [],
		"order": [],
		"columns": [],
		"column-fill": [],
		"column-rule": [],
		"column-rule-width": [],
		"column-rule-style": [],
		"column-rule-color": [],
		"column-span": [],
		"column-count": [],
		"column-width": [],
		"backface-visibility": [],
		"perspective": [],
		"perspective-origin": [],
		"transform": [],
		"transform-origin": [],
		"transform-style": [],
		"transition": [],
		"transition-delay": [],
		"transition-duration": [],
		"transition-property": [],
		"transition-timing-function": [],
		"visibility": [],
		"opacity": [],
		"z-index": [],
		"margin": [],
		"margin-top": [],
		"margin-right": [],
		"margin-bottom": [],
		"margin-left": [],
		"margin-block": [],
		"margin-block-start": [],
		"margin-block-end": [],
		"margin-inline": [],
		"margin-inline-start": [],
		"margin-inline-end": [],
		"outline": [],
		"outline-offset": [],
		"outline-width": [],
		"outline-style": [],
		"outline-color": [],
		"border": [],
		"border-top": [],
		"border-right": [],
		"border-bottom": [],
		"border-left": [],
		"border-width": [],
		"border-top-width": [],
		"border-right-width": [],
		"border-bottom-width": [],
		"border-left-width": [],
		"border-block": [],
		"border-block-width": [],
		"border-block-style": [],
		"border-block-color": [],
		"border-block-start": [],
		"border-block-start-width": [],
		"border-block-start-style": [],
		"border-block-start-color": [],
		"border-block-end": [],
		"border-block-end-width": [],
		"border-block-end-style": [],
		"border-block-end-color": [],
		"border-inline": [],
		"border-inline-width": [],
		"border-inline-style": [],
		"border-inline-color": [],
		"border-inline-start": [],
		"border-inline-start-width": [],
		"border-inline-start-style": [],
		"border-inline-start-color": [],
		"border-inline-end": [],
		"border-inline-end-width": [],
		"border-inline-end-style": [],
		"border-inline-end-color": [],
		"border-style": [],
		"border-top-style": [],
		"border-right-style": [],
		"border-bottom-style": [],
		"border-left-style": [],
		"border-radius": [],
		"border-top-left-radius": [],
		"border-top-right-radius": [],
		"border-bottom-left-radius": [],
		"border-bottom-right-radius": [],
		"border-start-start-radius": [],
		"border-start-end-radius": [],
		"border-end-start-radius": [],
		"border-end-end-radius": [],
		"border-color": [],
		"border-top-color": [],
		"border-right-color": [],
		"border-bottom-color": [],
		"border-left-color": [],
		"border-image": [],
		"border-image-source": [],
		"border-image-width": [],
		"border-image-outset": [],
		"border-image-repeat": [],
		"border-image-slice": [],
		"box-shadow": [],
		"isolation": [],
		"mix-blend-mode": [],
		"background": [],
		"background-attachment": [],
		"background-clip": [],
		"background-color": [],
		"background-image": [],
		"background-blend-mode": [],
		"background-origin": [],
		"background-position": [],
		"background-repeat": [],
		"background-size": [],
		"cursor": [],
		"padding": [],
		"padding-top": [],
		"padding-right": [],
		"padding-bottom": [],
		"padding-left": [],
		"padding-block": [],
		"padding-block-start": [],
		"padding-block-end": [],
		"padding-inline": [],
		"padding-inline-start": [],
		"padding-inline-end": [],
		"block-size": [], // Shifted (new position)
		"min-block-size": [], // Shifted (new position)
		"max-block-size": [], // Shifted (new position)
		"inline-size": [], // Shifted (new position)
		"min-inline-size": [], // Shifted (new position)
		"max-inline-size": [], // Shifted (new position)
		"width": [],
		// "block-size": [], // Shifted (previous position)
		"min-width": [],
		// "min-block-size": [], // Shifted (previous position)
		"max-width": [],
		// "max-block-size": [], // Shifted (previous position)
		"height": [],
		// "inline-size": [], // Shifted (previous position)
		"min-height": [],
		// "min-inline-size": [], // Shifted (previous position)
		"max-height": [],
		// "max-inline-size": [], // Shifted (previous position)
		"overflow": [],
		"overflow-block": [], // Added
		"overflow-inline": [], // Added
		"overflow-x": [],
		"overflow-y": [],
		"resize": [],
		"list-style": [],
		"list-style-type": [],
		"list-style-position": [],
		"list-style-image": [],
		"caption-side": [],
		"table-layout": [],
		"border-collapse": [],
		"border-spacing": [],
		"empty-cells": [],
		"animation": [],
		"animation-name": [],
		"animation-duration": [],
		"animation-timing-function": [],
		"animation-delay": [],
		"animation-iteration-count": [],
		"animation-direction": [],
		"animation-fill-mode": [],
		"animation-play-state": [],
		"vertical-align": [],
		"direction": [],
		"tab-size": [],
		"text-align": [],
		"text-align-last": [],
		"text-justify": [],
		"text-indent": [],
		"text-transform": [],
		"text-decoration": [],
		"text-decoration-color": [],
		"text-decoration-line": [],
		"text-decoration-style": [],
		"text-rendering": [],
		"text-shadow": [],
		"text-overflow": [],
		"line-height": [],
		"word-spacing": [],
		"letter-spacing": [],
		"white-space": [],
		"word-break": [],
		"word-wrap": [],
		"color": [],
		"font": [],
		"font-family": [],
		"font-kerning": [],
		"font-size": [],
		"font-size-adjust": [],
		"font-stretch": [],
		"font-weight": [],
		"font-smoothing": [],
		"osx-font-smoothing": [],
		"font-variant": [],
		"font-style": [],
		"content": [],
		"quotes": [],
		"counter-reset": [],
		"counter-increment": [],
		"page-break-before": [],
		"page-break-after": [],
		"page-break-inside": [],
		"pointer-events": [],
		"will-change": [],
	},
}

// https://github.com/cahamilton/css-property-sort-order-smacss/blob/master/src/index.ts
// commit: d0f7f45bb51f9245bcf27de0c68ffb99b33948e0
export const smacssConfigOrder: StylelintConfigOrder = {
	config: {
		...baseConfig,
		"extends": ["stylelint-config-property-sort-order-smacss"],
	},
	order: {
		"content": [],
		"quotes": [],
		"display": [],
		"visibility": [],
		"position": [],
		"z-index": [],
		"inset": [], // Added
		"inset-block": [], // Added
		"inset-block-start": [], // Added
		"inset-block-end": [], // Added
		"inset-inline": [], // Added
		"inset-inline-start": [], // Added
		"inset-inline-end": [], // Added
		"top": [],
		"right": [],
		"bottom": [],
		"left": [],
		"box-sizing": [],
		"grid": [],
		"grid-after": [],
		"grid-area": [],
		"grid-auto-columns": [],
		"grid-auto-flow": [],
		"grid-auto-rows": [],
		"grid-before": [],
		"grid-column": [],
		"grid-column-end": [],
		"grid-column-gap": [],
		"grid-column-start": [],
		"grid-columns": [],
		"grid-end": [],
		"grid-gap": [],
		"grid-row": [],
		"grid-row-end": [],
		"grid-row-gap": [],
		"grid-row-start": [],
		"grid-rows": [],
		"grid-start": [],
		"grid-template": [],
		"grid-template-areas": [],
		"grid-template-columns": [],
		"grid-template-rows": [],
		"flex": [],
		"flex-basis": [],
		"flex-direction": [],
		"flex-flow": [],
		"flex-grow": [],
		"flex-shrink": [],
		"flex-wrap": [],
		"align-content": [],
		"align-items": [],
		"align-self": [],
		"justify-content": [],
		"order": [],
		"width": [],
		"min-width": [],
		"max-width": [],
		"height": [],
		"min-height": [],
		"max-height": [],
		"block-size": [],
		"min-block-size": [],
		"max-block-size": [],
		"inline-size": [],
		"min-inline-size": [],
		"max-inline-size": [],
		"margin": [],
		"margin-top": [],
		"margin-right": [],
		"margin-bottom": [],
		"margin-left": [],
		"margin-block": [],
		"margin-block-start": [],
		"margin-block-end": [],
		"margin-inline": [],
		"margin-inline-start": [],
		"margin-inline-end": [],
		"padding": [],
		"padding-top": [],
		"padding-right": [],
		"padding-bottom": [],
		"padding-left": [],
		"padding-block": [],
		"padding-block-start": [],
		"padding-block-end": [],
		"padding-inline": [],
		"padding-inline-start": [],
		"padding-inline-end": [],
		"float": [],
		"clear": [],
		"overflow": [],
		"overflow-block": [], // Added
		"overflow-inline": [], // Added
		"overflow-x": [],
		"overflow-y": [],
		"clip": [],
		"zoom": [],
		"columns": [],
		"column-gap": [],
		"column-fill": [],
		"column-rule": [],
		"column-span": [],
		"column-count": [],
		"column-width": [],
		"table-layout": [],
		"empty-cells": [],
		"caption-side": [],
		"border-spacing": [],
		"border-collapse": [],
		"list-style": [],
		"list-style-position": [],
		"list-style-type": [],
		"list-style-image": [],
		"transform": [],
		"transform-box": [],
		"transform-origin": [],
		"transform-style": [],
		"backface-visibility": [],
		"perspective": [],
		"perspective-origin": [],
		"transition": [],
		"transition-property": [],
		"transition-duration": [],
		"transition-timing-function": [],
		"transition-delay": [],
		"animation": [],
		"animation-name": [],
		"animation-duration": [],
		"animation-play-state": [],
		"animation-timing-function": [],
		"animation-delay": [],
		"animation-iteration-count": [],
		"animation-direction": [],
		"border": [],
		"border-block": [], // Added
		"border-block-start": [], // Added
		"border-block-end": [], // Added
		"border-inline": [], // Added
		"border-inline-start": [], // Added
		"border-inline-end": [], // Added
		"border-top": [],
		"border-right": [],
		"border-bottom": [],
		"border-left": [],
		"border-width": [],
		"border-block-width": [], // Added
		"border-block-start-width": [], // Added
		"border-block-end-width": [], // Added
		"border-inline-width": [], // Added
		"border-inline-start-width": [], // Added
		"border-inline-end-width": [], // Added
		"border-top-width": [],
		"border-right-width": [],
		"border-bottom-width": [],
		"border-left-width": [],
		"border-style": [],
		"border-block-style": [], // Added
		"border-block-start-style": [], // Added
		"border-block-end-style": [], // Added
		"border-inline-style": [], // Added
		"border-inline-start-style": [], // Added
		"border-inline-end-style": [], // Added
		"border-top-style": [],
		"border-right-style": [],
		"border-bottom-style": [],
		"border-left-style": [],
		"border-radius": [],
		"border-start-start-radius": [], // Added
		"border-start-end-radius": [], // Added
		"border-end-start-radius": [], // Added
		"border-end-end-radius": [], // Added
		"border-top-left-radius": [],
		"border-top-right-radius": [],
		"border-bottom-right-radius": [],
		"border-bottom-left-radius": [],
		"border-color": [],
		"border-block-color": [], // Added
		"border-block-start-color": [], // Added
		"border-block-end-color": [], // Added
		"border-inline-color": [], // Added
		"border-inline-start-color": [], // Added
		"border-inline-end-color": [], // Added
		"border-top-color": [],
		"border-right-color": [],
		"border-bottom-color": [],
		"border-left-color": [],
		"outline": [],
		"outline-color": [],
		"outline-offset": [],
		"outline-style": [],
		"outline-width": [],
		"stroke-width": [],
		"stroke-linecap": [],
		"stroke-dasharray": [],
		"stroke-dashoffset": [],
		"stroke": [],
		"opacity": [],
		"background": [],
		"background-attachment": [],
		"background-clip": [],
		"background-color": [],
		"background-image": [],
		"background-repeat": [],
		"background-position": [],
		"background-size": [],
		"box-shadow": [],
		"fill": [],
		"color": [],
		"font": [],
		"font-family": [],
		"font-size": [],
		"font-size-adjust": [],
		"font-smoothing": [],
		"font-stretch": [],
		"font-style": [],
		"font-variant": [],
		"font-weight": [],
		"font-emphasize": [],
		"font-emphasize-position": [],
		"font-emphasize-style": [],
		"letter-spacing": [],
		"line-height": [],
		// "list-style": [], // Duplicate
		"text-align": [],
		"text-align-last": [],
		"text-decoration": [],
		"text-decoration-color": [],
		"text-decoration-line": [],
		"text-decoration-style": [],
		"text-indent": [],
		"text-justify": [],
		"text-overflow": [],
		"text-overflow-ellipsis": [],
		"text-overflow-mode": [],
		"text-rendering": [],
		"text-outline": [],
		"text-shadow": [],
		"text-transform": [],
		"text-wrap": [],
		"word-wrap": [],
		"word-break": [],
		"text-emphasis": [],
		"text-emphasis-color": [],
		"text-emphasis-style": [],
		"text-emphasis-position": [],
		"vertical-align": [],
		"white-space": [],
		"word-spacing": [],
		"hyphens": [],
		"src": [],
		"tab-size": [],
		"counter-reset": [],
		"counter-increment": [],
		"resize": [],
		"cursor": [],
		"pointer-events": [],
		"speak": [],
		"user-select": [],
		"nav-index": [],
		"nav-up": [],
		"nav-right": [],
		"nav-down": [],
		"nav-left": [],
	},
}
